# Generated by Django 5.2 on 2025-06-18 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindbridge_career', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='salary_max',
            new_name='salary',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_min',
        ),
    ]
