# Generated by Django 5.2 on 2025-05-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindbridge_career', '0002_alter_application_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD ($)'), ('EUR', 'EUR (€)'), ('RUB', 'RUB (₽)'), ('KZT', 'KZT (₸)')], default='USD', max_length=3),
        ),
    ]
