# Generated by Django 5.2 on 2025-06-18 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindbridge_career', '0003_remove_vacancy_company_vacancy_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
