# Generated by Django 5.2 on 2025-06-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindbridge_auth', '0002_alter_userprofile_options_userprofile_cover_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
