# Generated by Django 5.0.2 on 2025-04-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_discussion_host'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
    ]
