# Generated by Django 5.2.3 on 2025-06-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_answer_parent_answer_answer_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_discussion',
            field=models.BooleanField(default=False),
        ),
    ]
