# Generated by Django 5.1.6 on 2025-03-22 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_customtag_taggeditem_alter_discussion_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='parent',
        ),
    ]
