# Generated by Django 5.2 on 2025-04-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_country_city_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (max 2MB)', null=True, upload_to='avatars/'),
        ),
    ]
