# Generated by Django 5.2 on 2025-04-28 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindbridge_library', '0002_videos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
    ]
